### ISSUE TITLE
Line offset 0 or 1 quirk/issue/query

### ISSUE THREAD

**Issue by acotty** [eranif/dbgd#3]
The breakpoints work with a line number starting offset of 1.
The OnStopped(DAPEvent& event) when a breakpoint is hit has the event line number starting with an offset of 0.
The OnStackTrace(DAPEvent& event) I have not looked at it yet.

This seems a bit strange that there is a difference in the line starting offsets. I would have expected it to be 0 or 1, but not both.

Is this correct or have I missed something?
Are there any other inconsistencies?

I am thinking it may be an idea to create an readme some sort to include some of the issues and results like this and the previous issue to allow other devs read it instead of going through all of the issues. This will only be usefull if there are other projects that will use the library otherwise it will be a waste of time. I do not know if there are other IDE/debuggers that use wxWidgets and therefore would find the DLL useful.

**Comment by eranif** [comment]
You can change it in the Initialize request. I am not sure that I am exposing this to the end user, but this can be fixed
I doubt this project will be used many other developers, probably few people nothing more. 

Its for people who are writing IDEs/Debuggers/Editors - its not a common thing to see (and are using wxWigdets)

**Comment by acotty** [comment]
You are not exposing any of the InitializeRequest options to the end user. The client.cpp Initialize function is:

```
void dap::Client::Initialize()
{
    // Send initialize request
    InitializeRequest req = MakeRequest<InitializeRequest>();
    req.arguments.clientID = "dbgcli";
    SendRequest(req);
    m_handshake_state = eHandshakeState::kInProgress;
}
```

**Comment by acotty** [comment]
Thanks. I will grab the updated source tomorrow.
