### ISSUE TITLE
Linux workspace build failing

### ISSUE THREAD

**Issue by acotty** [eranif/dbgd#4]
On Windows the workspace builds okay.

On WSL2 using Ubuntu and GCC 11.1 or Xubuntu 20.04 and GCC 11.1 I get the following error when I try to build via the wxdap-linux.workspace:
/bin/sh: 1: cd: can't cd to build-debug
=== build completed successfully (0 errors, 0 warnings) ===

On Linus should I be using using the workspace or cmake or make?

The reason I am trying to build on Linux is that when I try to build the DLL using the linux C::B project I am working on I get the error below and I want to check if I get the same error with the CodeLite workspace.

```
-------------- Build: Debugger WXDAP in Debugger WXDAP DLL unix (compiler: GNU GCC Compiler)---------------

g++ -Wall -std=gnu++17 -g -O0 -ggdb -fPIC -isystem/usr/lib/x86_64-linux-gnu/wx/include/gtk3-unicode-3.0 -isystem/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -DBUILDING_PLUGIN -I. -I/mnt/d/Andrew_Development/Work_Installers/CodeBLocks_Private_Experimental/src/include -c /mnt/d/Andrew_Development/Work_Installers/CodeBLocks_Private_Experimental/src/plugins/contrib-wip/DebugAdapterProtocol/dap.cpp -o /mnt/d/Andrew_Development/Work_Installers/CodeBLocks_Private_Experimental/src/.objs31_64/debugger_WXDAP/dap.o

/mnt/d/Andrew_Development/Work_Installers/CodeBLocks_Private_Experimental/src/plugins/contrib-wip/DebugAdapterProtocol/dap.cpp: In static member function ‘static dap::ObjGenerator& dap::ObjGenerator::Get()’:
/mnt/d/Andrew_Development/Work_Installers/CodeBLocks_Private_Experimental/src/plugins/contrib-wip/DebugAdapterProtocol/dap.cpp:87:25: error: use of deleted function ‘dap::ObjGenerator::ObjGenerator()’
   87 |     static ObjGenerator generator;
      |                         ^~~~~~~~~

```

**Comment by eranif** [comment]
There are 2 workspaces provided. You should use the one named `wxdap-linux` (which is a CodeLite file system workspace that I configured to run  `cmake` command line commands). If you are not using CodeLite, then you should use the `CMake`:

```bash
mkdir -p build-debug
cd build-debug
cmake .. -DCMAKE_BUILD_TYPE=Debug
make -j$(nproc)
```

(same goes for macOS)

**Comment by acotty** [comment]
I am still working on this, but I think I may have a lead on the underlying issue I am seeing on Linux and it looks very similar to the following CodeLite issue:
https://github.com/eranif/codelite/issues/2769

I did a quick and dirty hack and changed the std::unordered_map to std::map along with the include files and I get the DAP so to build. This is not the right way, but it indicated to me that the project file I am using is okay and that the issue is code related. I need to look at issue 2769 and see what was done and give it a try.

**Comment by acotty** [comment]
Checked out issue 2769 and ported the change and created https://github.com/eranif/dbgd/pull/6 with the changes in it.

Once PR merged this issue can be closed.

**Comment by acotty** [comment]
Thanks very much for working on this yesterday. The compilation now works on all three OS's (Windows, Linux and MacOS). 

I can now do some rudimentary debugging on the MacOS using C::B now. Breakpoints, simple watches and call stack are wired with about the same level of functionality as the demo app.

**Comment by eranif** [comment]
That's great to hear. I too did some progress wiring it into CodeLite. Attached is a screenshot. I am also attaching a screenshot of the settings dialog which I am currently using to define a dap server within CodeLite

![dap-current-progress](https://user-images.githubusercontent.com/3677711/177196776-b6f562d0-9f44-42e7-99ef-b7d42787d8da.png)
