### ISSUE TITLE
Mac build fails due to #include <tr1/memory> instead of #include <memory>

### ISSUE THREAD

**Issue by acotty** [eranif/dbgd#5]
When building on the Mac the <tr1/memory file cannot be found. If you change the include to <memory> it builds.

Info on this and discussions on it can be seen in the following issue:
     https://github.com/cuberite/cuberite/issues/424

I have also tested the changes on Windows with MSYS2 mingw64 and the code builds.

**Comment by acotty** [comment]
I will pull and test the changes today.

**Comment by eranif** [comment]
There is no include `<tr1/memory>` in the code, can you point me to the location or better yet, can you paste here the build error you are getting?

**Comment by acotty** [comment]
I have no idea what I was thinking when I created the issue as I was comparing my plugin directory.... Too much comparing I think.

BTW I have built the dll on mac, but need to figure out why I am not linking correctly to wxWidgets.
