### ISSUE TITLE
Missing SetExceptionBreakpointsRequest for exception capture/intercept

### ISSUE THREAD

**Issue by acotty** [eranif/dbgd#7]
I cannot find out how to enable the library to capture/intercept exceptions to cause a ‘stopped’ event to be fired. If I have missed something could you please let me know how I can enable/setup the library so it can capture/intercept exceptions.

If I have read the protocol the function to setup exception capture/intercept is "SetExceptionBreakpointsRequest".

The reason I am after this is that on the MacOS C::B crashes when performing certain "things" (there are a number of logged tickets for MacOS crashes over the years that have not been fixed). I find the easiest way to try find where the issue is is to case the crash and if the debugger can stop and show the call stack it will narrow the area(s) to look at. "Try" in the previous sentence if everything works correctly.

**Comment by eranif** [comment]
I did not add support for `SetExceptionBreakpointsRequest` yet, however, I assumed that the debugger should stop when an exception occurs. I ran a small test and indeed it stopped (running under `lldb-vscode`):

![exception](https://user-images.githubusercontent.com/3677711/177264484-b835bd02-4820-43ab-9932-806bda304d3f.png)


Here is the protocol exchange between the library and the dap server:
```bash
[09:38:46:900 DEBUG] --> {"seq":37,"type":"request","command":"next","arguments":{"threadId":22512,"granularity":"line"}}
[09:38:46:900 DEBUG] <-- {"command":"next","request_seq":37,"seq":0,"success":true,"type":"response"}
[09:38:46:906 DEBUG] <-- {"body":{"allThreadsStopped":true,"preserveFocusHint":false,"reason":"exception","threadCausedFocus":true,"threadId":22512},"event":"stopped","seq":0,"type":"event"}
```

As you can see, once I did `Next` and stepped over the `throw` line, I received a `stopped` event with reason `exception`
can you share that protocol exchange that fails for you?

**Comment by eranif** [comment]
FYI: I ran similar test on macOS (macOS Monterey, 12.4, M1, using lldb-vscode installed from `brew`)
same thing: the debugger stopped and provided backtrace similar to the above

**Comment by acotty** [comment]
I did the test on Windows with C:\msys64\mingw64\bin\lldb-vscode.exe

The exception I tried was:
    throw std::overflow_error("Exception throw testing");

I will do some more testing to see if I can figure out what is going on, but it will be tomorrow as I am working on getting the DLL and then the plugin building in the not very nice C::B bootstrap/configure/make process.

**Comment by eranif** [comment]
so, are you saying that `std::overflow_error` does not work as expected?
UPDATE:
At least on mac (will try on Windows later), the results are the same. The debugger stops with reason `exception`

**Comment by acotty** [comment]
Finally back to this.  Exception capturing/intercepting works on Linux. But not on Windows. I changed the exception to throw "std::exception();" and it still did not work on Windows.

The following are the two command used to build the test exe with the exception and other simple debug tests I use:
clang++.exe -Wall -fexceptions -Og -g -I.\ -IC:\msys64\clang64\include\ -c D:\Andrew_Development\Z_Testing_Apps\Clang_printf\main.cpp -o obj\main.o
clang++.exe  -o bin\clang_Printf.exe obj\main.o

**Comment by acotty** [comment]
If I run the exe using  c:\msys64\mingw64\bin\lldb.exe it looks like the LLDB stops on the exception as I added printf before the std::exception() line and after. The before was printed on a seperate command prompt. 

The following shows the test I ran and the LLDB commands used and the exception output:
$ c:\msys64\mingw64\bin\lldb.exe clang_Printf.exe
(lldb) target create "clang_Printf.exe"
Current executable set to 'D:\Andrew_Development\Z_Testing_Apps\Clang_printf\bin\clang_Printf.exe' (x86_64).
(lldb) break set -E C++
Breakpoint 1: no locations (pending).
(lldb) run
2 locations added to breakpoint 1
(lldb) Process 17272 launched: 'D:\Andrew_Development\Z_Testing_Apps\Clang_printf\bin\clang_Printf.exe' (x86_64)
Process 17272 stopped
* thread #1, stop reason = breakpoint 1.1
    frame #0: 0x00007ff97683b240 libstdc++-6.dll`__cxa_throw
libstdc++-6.dll`__cxa_throw:
->  0x7ff97683b240 <+0>: pushq  %rdi
    0x7ff97683b241 <+1>: pushq  %rsi
    0x7ff97683b242 <+2>: pushq  %rbx
    0x7ff97683b243 <+3>: subq   $0x20, %rsp
(lldb)

So it looks like on Windows the lldb does handle exception capture/intercepting. I wonder if on Windows the exception handling is off by default, just a thought.

**Comment by eranif** [comment]
i did test this on windows, and it works. note that there are 2 flavors of lldb-vscode and clang. make sure you are using clang and lldb-vscode from the clang64 repo and not from mingw64.


i.e.

/clang64/bin/lldb-vscode

and NOT 

/mingw64/bin/lldb-vscode

same goes with clang

**Comment by acotty** [comment]
Thanks. It works using the clang64 directory. 

I should probably create a MSYS2 issue as the lldb-vscode should work the same..... and see what the response is.

**Comment by eranif** [comment]
is still an issue? can we close this

**Comment by acotty** [comment]
Closed as it looks like a package/build issue with the /mingw64/bin/lldb-vscode not working the same as the /clang64/bin/lldb-vscode
