### ISSUE TITLE
Support for the GDB/MI interface

### ISSUE THREAD

**Issue by 0xDagal** [eranif/dbgd#9]
> gdb server using the DAP protocol (Debug Adapter Protocol)

Is it really ? I ask because I'm a Vim user and I'm searching for a way to use [termdebug](https://github.com/vim/vim/blob/master/runtime/pack/dist/opt/termdebug/plugin/termdebug.vim) with DAP.

Termdebug can use any server that implements the GDB/MI interface so if yours can I will use it right away.

**Comment by eranif** [comment]
I wrote this library to support the DAP protocol with CodeLite IDE.
I am in the process of migrating our code base to completely use DAP

The implementation of the DAP protocol (using wxWidgets event based code) is complete
The next step will be to write a gdb DAP server, so I can remove my old gdb/mi interaction code from CodeLite code base

**Comment by 0xDagal** [comment]
Nice if I can help in any way (I'm not a Cpp dev) let me know 😁

**Comment by eranif** [comment]
FYI: gdb v14 (should be release soon) supports the dap protocol, in addition, `cpptools` by microsoft also is supporting gdb
https://docs.codelite.org/plugins/dap/#install-cpptools

**Comment by 0xDagal** [comment]
@eranif didn't know thanks 😁 

_Sent from my FP3 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_
